### ISSUE TITLE
/logout

### ISSUE THREAD

**Issue by ichhasseeuch** [Eicosaan/block#3]
disallow users/members to use this command, it exist other fishy bug,
but i forgot how it works

**Comment by Rootkitee** [comment]
What happens if a user/member uses this command?

**Comment by ichhasseeuch** [comment]
idk how the bug works, but  u can steal  authed members/admins and can change the password

**Comment by Rootkitee** [comment]
And this happens after the user execs "/logout" ?

**Comment by Eicosaan** [comment]
not exactly, but it prevents it.

**Comment by ichhasseeuch** [comment]
fixed
